<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="5" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-07-18T12:43:16 IST" name="Default suite" finished-at="2024-07-18T12:46:10 IST" duration-ms="174189">
    <groups>
      <group name="Purchase">
        <method signature="projectReTestNg.submitOrder(java.util.HashMap)[pri:0, instance:MavenProject.MavenProject.projectReTestNg@7bba5817]" name="submitOrder" class="MavenProject.MavenProject.projectReTestNg"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2024-07-18T12:43:16 IST" name="Default test" finished-at="2024-07-18T12:46:10 IST" duration-ms="174189">
      <class name="MavenProject.MavenProject.projectReTestNg">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:MavenProject.MavenProject.projectReTestNg@7bba5817]" started-at="2024-07-18T12:43:16 IST" name="launchApplication" finished-at="2024-07-18T12:43:29 IST" duration-ms="12715" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:MavenProject.MavenProject.projectReTestNg@7bba5817]" started-at="2024-07-18T12:43:29 IST" name="submitOrder" data-provider="getData" finished-at="2024-07-18T12:44:11 IST" duration-ms="42171" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=khadeer@gmail.com, productName=ADIDAS ORIGINAL, Password=Default@123}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="closeApplication()[pri:0, instance:MavenProject.MavenProject.projectReTestNg@7bba5817]" started-at="2024-07-18T12:44:11 IST" name="closeApplication" finished-at="2024-07-18T12:44:12 IST" duration-ms="602" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:MavenProject.MavenProject.projectReTestNg@7bba5817]" started-at="2024-07-18T12:44:12 IST" name="launchApplication" finished-at="2024-07-18T12:44:18 IST" duration-ms="5761" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:MavenProject.MavenProject.projectReTestNg@7bba5817]" started-at="2024-07-18T12:44:18 IST" name="submitOrder" data-provider="getData" finished-at="2024-07-18T12:44:40 IST" duration-ms="22331" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=khadeer1@gmail.com, productName=ZARA COAT 3, Password=Default@123}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="closeApplication()[pri:0, instance:MavenProject.MavenProject.projectReTestNg@7bba5817]" started-at="2024-07-18T12:44:40 IST" name="closeApplication" finished-at="2024-07-18T12:44:41 IST" duration-ms="851" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:MavenProject.MavenProject.projectReTestNg@7bba5817]" started-at="2024-07-18T12:44:41 IST" name="launchApplication" finished-at="2024-07-18T12:44:58 IST" duration-ms="16982" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="orderHistoryTest()[pri:0, instance:MavenProject.MavenProject.projectReTestNg@7bba5817]" started-at="2024-07-18T12:44:58 IST" name="orderHistoryTest" finished-at="2024-07-18T12:45:30 IST" depends-on-methods="MavenProject.MavenProject.projectReTestNg.submitOrder" duration-ms="31789" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at MavenProject.MavenProject.projectReTestNg.orderHistoryTest(projectReTestNg.java:53)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orderHistoryTest -->
        <test-method is-config="true" signature="closeApplication()[pri:0, instance:MavenProject.MavenProject.projectReTestNg@7bba5817]" started-at="2024-07-18T12:45:30 IST" name="closeApplication" finished-at="2024-07-18T12:45:30 IST" duration-ms="435" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:MavenProject.MavenProject.projectReTestNg@7bba5817]" started-at="2024-07-18T12:45:30 IST" name="launchApplication" finished-at="2024-07-18T12:45:39 IST" duration-ms="8903" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="orderHistoryTest()[pri:0, instance:MavenProject.MavenProject.projectReTestNg@7bba5817]" started-at="2024-07-18T12:45:39 IST" name="orderHistoryTest" finished-at="2024-07-18T12:46:10 IST" depends-on-methods="MavenProject.MavenProject.projectReTestNg.submitOrder" duration-ms="30800" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at MavenProject.MavenProject.projectReTestNg.orderHistoryTest(projectReTestNg.java:53)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orderHistoryTest -->
        <test-method is-config="true" signature="closeApplication()[pri:0, instance:MavenProject.MavenProject.projectReTestNg@7bba5817]" started-at="2024-07-18T12:46:10 IST" name="closeApplication" finished-at="2024-07-18T12:46:10 IST" duration-ms="345" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
      </class> <!-- MavenProject.MavenProject.projectReTestNg -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
